name: Ejecutar scripts diarios 2

on:
  schedule:
    - cron: '5 7 * * *'  # Todos los días a las 07:05 UTC
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper Investing
        run: python scrapper_invest.py

      - name: Esperar 5 minutos
        run: sleep 300

      - name: Ejecutar análisis de crecimiento
        run: python Crecimiento.py

      - name: Ver archivos generados
        run: ls -R

      - name: Subir archivos actualizados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "📈 Datos actualizados automáticamente" || echo "Sin cambios"
          git push
